name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        shell: bash
        run: |
          set -e
          rm -rf node_modules package-lock.json ~/.npm/_cacache
          npm install --no-audit --no-fund

      - name: Run linter
        run: npm run lint